
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 13.2 EDK_O.61xd
* DO NOT EDIT.
*
* Copyright (c) 1995-2011 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_LED_DEVICE_ID,
		XPAR_LED_BASEADDR,
		XPAR_LED_INTERRUPT_PRESENT,
		XPAR_LED_IS_DUAL
	},
	{
		XPAR_SWITCHES_DEVICE_ID,
		XPAR_SWITCHES_BASEADDR,
		XPAR_SWITCHES_INTERRUPT_PRESENT,
		XPAR_SWITCHES_IS_DUAL
	}
};


